source 'https://github.com/CocoaPods/Specs.git'
pod 'SDWebImage', '~>3.6'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh'
pod 'FMDB', '~> 2.5'
pod 'HMSegmentedControl', '~> 1.5.2'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
pod 'AFNetworking', '~> 2.6.0'
